installed_at: '2026-01-16T15:25:19+00:00'
skill_id: claudekit/frontend-design-pro-demo/frontend-design-pro
git_repo: https://github.com/claudekit/frontend-design-pro-demo.git
skill_path: /main/skills/frontend-design-pro
git_sha: 756b8d99618b2c4e8a90c89a99f678009468aae3
skilz_version: 1.7.0
install_mode: copy
canonical_path: null
