using PersonalBrandAssistant.Domain.ValueObjects;

namespace PersonalBrandAssistant.Domain.Tests.ValueObjects;

public class ContentMetadataTests
{
    [Fact]
    public void ContentMetadata_WithAllFields_CreatesValidObject()
    {
        var metadata = new ContentMetadata
        {
            Tags = ["ai", "branding"],
            SeoKeywords = ["personal brand"],
            PlatformSpecificData = new Dictionary<string, string> { ["twitter"] = "thread" },
            AiGenerationContext = "Generated by Claude",
            TokensUsed = 1500,
            EstimatedCost = 0.05m,
        };

        Assert.Equal(2, metadata.Tags.Count);
        Assert.Single(metadata.SeoKeywords);
        Assert.Equal("Generated by Claude", metadata.AiGenerationContext);
        Assert.Equal(1500, metadata.TokensUsed);
        Assert.Equal(0.05m, metadata.EstimatedCost);
    }

    [Fact]
    public void ContentMetadata_WithNullOptionalFields_IsValid()
    {
        var metadata = new ContentMetadata();

        Assert.Null(metadata.AiGenerationContext);
        Assert.Null(metadata.TokensUsed);
        Assert.Null(metadata.EstimatedCost);
    }

    [Fact]
    public void Tags_And_SeoKeywords_InitializeAsEmptyLists()
    {
        var metadata = new ContentMetadata();

        Assert.NotNull(metadata.Tags);
        Assert.Empty(metadata.Tags);
        Assert.NotNull(metadata.SeoKeywords);
        Assert.Empty(metadata.SeoKeywords);
    }
}
